version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: fsa-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=db-admin
      - MONGO_INITDB_ROOT_PASSWORD=dev_8u2mZecf8zONV5XU2oPnkzgcplvub7Yx0Optxmnbwq25Bp1onX
    command: mongod --quiet --logpath /dev/null
    restart: always
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - ./mongo_initial:/docker-entrypoint-initdb.d/
volumes:
  data:
    driver: local
