version: "3.8"
services:
  redis:
    image: redis:7.0.7
    container_name: fsa-redis
    restart: always
    networks:
      - app-network
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
    ports:
      - 6379:6379
    command: redis-server --appendonly yes --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes:
      - /tmp/redis/cache:/data
networks:
  app-network:
    driver: bridge
